In [1]:
a=[2,4,3,5,6]
a*2

[2, 4, 3, 5, 6, 2, 4, 3, 5, 6]

In [2]:
import numpy as np

In [3]:
b=np.array(a)

In [4]:
b**2

In [5]:
b.dtype,b.itemsize,b.shape,b.ndim

In [6]:
b=np.array(a,dtype=np.int16,ndmin=3,)
b.dtype,b.itemsize,b.shape

(dtype('int16'), 2, (1, 1, 5))

In [7]:
np.arange(0.1,17,0.1)

In [8]:
np.linspace(1,10,10)

In [9]:
2**np.linspace(1,10,10)

In [10]:
np.logspace(1,10,10,base=2)

array([    2.,     4.,     8.,    16.,    32.,    64.,   128.,   256.,
         512.,  1024.])

In [11]:
np.empty((2,3))

In [12]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [13]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [14]:
np.random.rand(3,3)

array([[ 0.7949021 ,  0.75915741,  0.46077426],
       [ 0.6919006 ,  0.31851035,  0.89479955],
       [ 0.00129706,  0.62134275,  0.19944316]])

In [15]:
np.random.chisquare(1,20)

array([  5.88291294e-01,   5.47599114e-01,   2.56369619e-02,
         6.85859062e-01,   1.40099632e+00,   5.75793251e-02,
         8.62109068e-01,   2.44539772e+00,   8.65701158e-01,
         3.15706015e+00,   1.55006987e+00,   1.23117102e-03,
         3.49348026e-01,   1.10692677e-01,   2.03480219e-01,
         1.63632797e-01,   3.41551075e-01,   6.72375409e-01,
         5.86219816e-01,   2.08274450e-01])

In [16]:
b=np.arange(1,17)

In [17]:
b.shape=(2,4,2)

In [18]:
b.reshape(4,2,2) # returns a new array with the shape

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [19]:
b.resize(2,2,4) #makes the changes locally

In [20]:
np.resize(b,(4)) # it returns a new arry of desired shape

array([1, 2, 3, 4])

In [21]:
b.shape=(4,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
b.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [23]:
np.transpose(b)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [24]:
c=np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
c.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
c.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [27]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
#b[3rd,2d,1d]
b[:,0]

array([ 1,  5,  9, 13])

In [29]:
b[::2,0]

array([1, 9])

In [30]:
b[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [31]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
b[[0,2,3],::2]

array([[ 1,  3],
       [ 9, 11],
       [13, 15]])

In [33]:
b[b%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [34]:
b[b>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [35]:
b.shape=(2,1,4,2,1)

In [36]:
b.T.shape

(1, 2, 4, 1, 2)

In [37]:
np.swapaxes(b,0,2).shape

(4, 1, 2, 2, 1)

In [38]:
np.rollaxis(b,2,0).shape

(4, 2, 1, 2, 1)

In [39]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [40]:
np.ravel(b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [41]:
x=b.flat
next(x),list(x)

(1, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])