In [1]:
import numpy as np
a=np.arange(1,7)
a.shape=(3,2)

In [2]:
from sklearn.decomposition.pca import PCA
algo=PCA(2)
algo.fit(a)
algo.transform(a)

array([[-2.82842712e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 2.82842712e+00,  2.22044605e-16]])

In [22]:
import numpy as np
m=np.mean(a,axis=0)
d=a-m
c=np.cov(d.T)
i,j=np.linalg.eig(c)
print('explained vari',i,'components',j,'mean',m)
np.dot(d,j.T)

explained vari [8. 0.] components [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] mean [3. 4.]


array([[ 0.        , -2.82842712],
       [ 0.        ,  0.        ],
       [ 0.        ,  2.82842712]])

In [12]:
algo.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [13]:
algo.mean_

array([3., 4.])

In [15]:
algo.explained_variance_

array([8., 0.])