In [1]:
import requests as s
dt=s.request('get','https://archive.ics.uci.edu/ml/machine-learning-databases/00327/.old.arff')

In [6]:
from scipy.io import arff
from io import StringIO
import pandas as pd

In [7]:
data=pd.DataFrame(arff.loadarff(StringIO(dt.text))[0])

In [9]:
for i in data.columns:
    data[i]=data[i].astype(dtype='i')

In [10]:
data.head()

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                  1           1                   0                 0   
1                  0           1                   0                 0   
2                  0           0                   0                 0   
3                  0           0                   0                 0   
4                  0           0                   1                 0   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                         1             -1                 -1              -1   
1                         0             -1                  0               1   
2                         0             -1                 -1              -1   
3                         0             -1                 -1              -1   
4                         0             -1                  1               1   

   Domain_registeration_length  Favicon   ...    popUpWidnow  Iframe  \
0                            0        0   ...              0       0   
1                            0        0   ...              0       0   
2                            0        0   ...              0       0   
3                            1        0   ...              0       0   
4                            0        0   ...              1       0   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1          1           -1         -1             0   
1             -1          1            0         -1             0   
2              0          1            1         -1             0   
3             -1          1            1         -1             0   
4             -1          1            0         -1             0   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                   1       1  
1                       1                   0       1  
2                       0                   1       1  
3                      -1                   0       1  
4                       1                   0      -1  

[5 rows x 31 columns]

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
from sklearn.decomposition import PCA

In [35]:
x=data.drop('Result',axis=1)
y=data['Result']
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts=train_test_split(x,y,test_size=0.2)

In [36]:
x.shape,y.shape

((2456, 30), (2456,))

In [37]:
algo=RandomForestClassifier()
algo.fit(x_tr,y_tr)
algo.score(x_ts,y_ts)

0.9715447154471545

In [49]:
alg=PCA(2)
alg.fit(x)
x_tr1=alg.transform(x_tr)
x_ts1=alg.transform(x_ts)
x_tr1.shape

(1964, 2)

In [39]:
algo.fit(x_tr1,y_tr)
algo.score(x_ts1,y_ts)

0.9146341463414634

In [162]:
import numpy as np
a=np.arange(1,7)
a.shape=(3,2)
c=np.mean(a.T,axis=1)
d=a-c
e=np.cov(d.T)
val,vect=np.linalg.eig(e)
vect.T.dot(d.T)
w=np.matlib.matrix(d)
k=np.matlib.matrix(vect.T)
w*k

matrix([[ 0.        , -2.82842712],
        [ 0.        ,  0.        ],
        [ 0.        ,  2.82842712]])

In [141]:
alg=PCA(2)
alg.fit(a)

alg.components_,alg.explained_variance_,alg.transform(a)

(array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]),
 array([8., 0.]),
 array([[-2.82842712e+00, -2.22044605e-16],
        [ 0.00000000e+00,  0.00000000e+00],
        [ 2.82842712e+00,  2.22044605e-16]]))

array([[6.66666667, 6.66666667],
       [6.66666667, 6.66666667]])

array([6.36396103, 0.70710678])